# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covid-19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid-19

   pod 'Alamofire', '~> 5.4'
   pod 'Charts'


end
