# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoPlayerTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoPlayerTest
  pod "Player", "~> 0.13.2"
  pod 'BMPlayer', '~> 1.3.0'
  pod 'FWPlayer'
  pod 'SwiftLint'
end
