# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindCVS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindCVS
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit' 

  target 'FindCVSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Stubber'
    pod 'Nimble' 
    pod 'RxBlocking'
    pod 'RxTest'
  end

end
