# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieReview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieReview
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'MovieReviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieReviewUITests' do
    # Pods for testing
  end

end
